### PR TITLE
1

### PR DESCRIPTION
**Pull request by 3kh00**

### CODE REVIEW

**Review by 3kh00 — COMMENTED** [review]
1

**Comment by Cattn** [comment]
does these commits fix it?

**Comment by Cattn** [comment]
I'm attempting to build it right now I'll add deploy buttons for other providers as well

**Comment by Cattn** [comment]
oh I see the issue with file-names

**Comment by Cattn** [comment]
I'm going to fix it by changing names so I can still integrate properly into the site, thanks for helpin out

**Pull request closed without merging**
